#!/usr/bin/env node
let process = require("process");
let child_process = require("child_process");
const { ESLint } = require("eslint");

function exec(name){
  return new Promise(function(resolve){
    child_process.exec(name, resolve);
  })
}

(async function main() {
  // 1. Create an instance.
  const eslint = new ESLint({ fix: false });

  await exec("git stash push -k");

  // 2. Lint files.
  const results = await eslint.lintFiles(["index.js"]);

  await exec("git stash pop");

  // 3. Format the results.
  const formatter = await eslint.loadFormatter("stylish");
  const resultText = formatter.format(results);

  // 4. Output it.
  console.log(resultText);

  for(let result of results){
    if(result.errorCount){
      process.exitCode = 1;
    }
  }
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});